version: '3.8'
services:
  db:
    image: mariadb:11
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: operaton
      MARIADB_USER: operaton
      MARIADB_PASSWORD: operaton
