version: '3.8'
services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: operaton
      MYSQL_USER: operaton
      MYSQL_PASSWORD: operaton
