name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build examples
        run: |
          set -e
          wait_for_port() {
            local port="$1"
            for i in {1..120}; do
              if nc -z localhost "$port"; then
                return 0
              fi
              sleep 3
            done
            return 1
          }
          wait_for_mysql() {
            local project="$1"
            for i in {1..120}; do
              if docker compose -p "$project" exec -T db mysqladmin ping -uoperaton -poperaton --silent; then
                return 0
              fi
              sleep 3
            done
            return 1
          }
          wait_for_mssql() {
            local project="$1"
            for i in {1..120}; do
              if docker compose -p "$project" exec -T db /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Passw0rd! -Q "SELECT 1" >/dev/null 2>&1; then
                return 0
              fi
              sleep 3
            done
            return 1
          }
          wait_for_db2() {
            local project="$1"
            for i in {1..120}; do
              if docker compose -p "$project" exec -T db bash -c 'id -u db2inst1 >/dev/null 2>&1 && su - db2inst1 -c "db2 connect to operaton >/dev/null 2>&1 && db2 connect reset >/dev/null 2>&1"'; then
                return 0
              fi
              sleep 10
            done
            return 1
          }
          for pom in $(find . -path './template' -prune -o -name pom.xml -print); do
            dir=$(dirname "$pom")
            project=$(echo "$dir" | sed 's#^\./##' | tr '/:.' '_')
            db=$(basename "$dir")
            if [ -f "$dir/docker-compose.yml" ]; then
              docker compose -p "$project" -f "$dir/docker-compose.yml" up -d
              case "$db" in
                postgres) port=5432 ;;
                mysql|mariadb) port=3306 ;;
                oracle) port=1521 ;;
                db2) port=50000 ;;
                sqlserver) port=1433 ;;
                *) port=0 ;;
              esac
                if [ "$port" -ne 0 ]; then
                  if ! wait_for_port "$port"; then
                    docker compose -p "$project" -f "$dir/docker-compose.yml" logs
                    exit 1
                  fi
                  case "$db" in
                    mysql|mariadb)
                      if ! wait_for_mysql "$project"; then
                        docker compose -p "$project" -f "$dir/docker-compose.yml" logs
                        exit 1
                      fi
                      ;;
                    db2)
                      if ! wait_for_db2 "$project"; then
                        docker compose -p "$project" -f "$dir/docker-compose.yml" logs
                        exit 1
                      fi
                      ;;
                    sqlserver)
                      if ! wait_for_mssql "$project"; then
                        docker compose -p "$project" -f "$dir/docker-compose.yml" logs
                        exit 1
                      fi
                      ;;
                  esac
                fi
            fi
            mvn -B -f "$pom" test
            if [ -f "$dir/docker-compose.yml" ]; then
              docker compose -p "$project" -f "$dir/docker-compose.yml" down -v
            fi
          done

