name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build examples
        run: |
          set -e
          wait_for_port() {
            local port="$1"
            echo "Waiting 10 seconds for port $port"
            sleep 10
            return 0
          }
          wait_for_mysql() {
            local project="$1"
            echo "Waiting 10 seconds for MySQL ($project)"
            sleep 10
            return 0
          }
          wait_for_mssql() {
            local project="$1"
            echo "Waiting 10 seconds for SQL Server ($project)"
            sleep 10
            return 0
          }
          wait_for_db2() {
            local project="$1"
            echo "Waiting 10 seconds for DB2 ($project)"
            sleep 10
            return 0
          }
          wait_for_oracle() {
            local project="$1"
            echo "Waiting 10 seconds for Oracle ($project)"
            sleep 10
            return 0
          }
          for pom in $(find . -path './template' -prune -o -name pom.xml -print); do
            dir=$(dirname "$pom")
            project=$(echo "$dir" | sed 's#^\./##' | tr '/:.' '_')
            db=$(basename "$dir")
            if [ -f "$dir/docker-compose.yml" ]; then
              docker compose -p "$project" -f "$dir/docker-compose.yml" up -d
              case "$db" in
                postgres) port=5432 ;;
                mysql|mariadb) port=3306 ;;
                oracle) port=1521 ;;
                db2) port=50000 ;;
                sqlserver) port=1433 ;;
                *) port=0 ;;
              esac
                if [ "$port" -ne 0 ]; then
                  if ! wait_for_port "$port"; then
                    docker compose -p "$project" -f "$dir/docker-compose.yml" logs
                    exit 1
                  fi
                    case "$db" in
                      mysql|mariadb)
                        if ! wait_for_mysql "$project"; then
                          docker compose -p "$project" -f "$dir/docker-compose.yml" logs
                          exit 1
                        fi
                        ;;
                      oracle)
                        if ! wait_for_oracle "$project"; then
                          docker compose -p "$project" -f "$dir/docker-compose.yml" logs
                          exit 1
                        fi
                        ;;
                      db2)
                        if ! wait_for_db2 "$project"; then
                          docker compose -p "$project" -f "$dir/docker-compose.yml" logs
                          exit 1
                        fi
                      ;;
                    sqlserver)
                      if ! wait_for_mssql "$project"; then
                        docker compose -p "$project" -f "$dir/docker-compose.yml" logs
                        exit 1
                      fi
                      ;;
                  esac
                fi
            fi
            mvn -B -f "$pom" test
            if [ -f "$dir/docker-compose.yml" ]; then
              docker compose -p "$project" -f "$dir/docker-compose.yml" down -v
            fi
          done

