name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build examples
        run: |
          for pom in $(find . -path './template' -prune -o -name pom.xml -print); do
            dir=$(dirname "$pom")
            if [ -f "$dir/docker-compose.yml" ]; then
              docker compose -f "$dir/docker-compose.yml" up -d
              # wait for the database to accept connections
              sleep 40
            fi
            mvn -B -f "$pom" test
            if [ -f "$dir/docker-compose.yml" ]; then
              docker compose -f "$dir/docker-compose.yml" down
            fi
          done

